server:
  port: 8888
zk:
  zul-view-resolver-prefix: /
  zul-view-resolver-suffix: .zul
  richlet-filter-mapping: /richlet/*
  homepage: index
spring:
  jmx:
    default-domain: springbook-zk
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.253.16:3306/zk?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: lzw719
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    naming:
#      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   #不加这句则默认为myisam引擎
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
