server:
  port: 8888
zk:
  zul-view-resolver-prefix: /zul
  zul-view-resolver-suffix: .zul
  richlet-filter-mapping: /richlet/*
  homepage: index
spring:
  jmx:
    default-domain: springbook-zk
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zk?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: lzw719
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  session:
    store-type: redis

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 10000
    timeout: 30000
#    naming:
#      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   #不加这句则默认为myisam引擎
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
